source 'https://rubygems.org'

gem 'berkshelf'
gem 'test-kitchen', :group => :integration
gem 'kitchen-vagrant', :group => :integration

gem "serverspec"
gem 'chefspec', '1.0.0'

gem 'cucumber', :group => :integration
gem 'rspec-expectations', :group => :integration
gem 'leibniz', :group => :integration


