source 'https://rubygems.org'

ruby '1.9.3'

gem 'rake', '10.1.0'
gem 'chef', '11.4.4'
gem 'chefspec', '1.0.0'
gem 'foodcritic', '2.1.0'
gem 'tailor'
gem 'cane'
gem 'chef-rewind'

gem "knife-spork", "1.0.17"
gem "berkshelf"

gem 'test-kitchen', "1.0.0.beta.3"
gem 'kitchen-vagrant'

gem 'cucumber'
gem 'leibniz'
#group :development do
gem 'chef-zero'
#end

